name: Build and Publish

on:
  push:
    branches:
      - master

jobs:
  build_docker_image:
    runs-on: ubuntu-latest

    steps: 
    - uses: actions/checkout@v2 

    - name: Build and Publish to Dockerhub
      uses: mr-smithers-excellent/docker-build-push@v2
      with:
        image: alext234/datascience
        registry: docker.io
        tag: latest
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}    

    - name: Build and Publish to Github packages
      uses: VaultVulp/gp-docker-action@1.0.1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }} 
        image-name: datascience
        image-tag: latest
